### ISSUE TITLE
Apply minor edits to README.md and vignette formatting

### ISSUE THREAD

**Issue by nturaga** [Jiefei-Wang/SharedObject#1]
This gist has a diff which can be applied using 

`git apply filename.diff`

https://gist.github.com/9782eb264ff7c3eae8703d78bfddff40. 

The diff, includes a typo in the README.md file, and vignette formatting so R markdown is rendered more appropriately.

**Comment by Jiefei-Wang** [comment]
Hi Nitash,

Thanks for your comments, I have apply the diff files in commit 
24ee4cbc183d809e4d97e2af67743a5a1dc26592

Jiefei
