### ISSUE TITLE
Sharing objects works only for objects with three and more elements

### ISSUE THREAD

**Issue by MilanFischer** [Jiefei-Wang/SharedObject#11]
Hello, 
I found that when I try to share vector or list with less than three elements, the sharing doesn't work.

Here is the working example with three element in the list:
`x <- list(A = c(0.5,1,1,5))`
`shared_x <- share(x)`
`is.shared(shared_x)`
`[1] TRUE`

However, if I use only two elements, the object is not shared:
`x <- list(A = c(0.5,1))`
`shared_x <- share(x)`
`is.shared(shared_x)`
`[1] FALSE`

Please, can you check it?

Anyway, I would like to say thank you for this great package! I found it as a great help for parallel processing.

Best,
Milan

**Comment by Jiefei-Wang** [comment]
Hi Milan,

Thanks for the issue. This is expected, we do not share the small object as you can not gain any performance benefit by sharing it. If you do want to share all objects, `minLength = 0L` can be used in `share` to enable the sharing.

Best,
Jiefei

**Comment by MilanFischer** [comment]
Hi Jiefei,
OK, in that case no issue at all.

Thank you for clarifying that.

Best,
Milan
