### ISSUE TITLE
Is it ok to share factor instead of character ?

### ISSUE THREAD

**Issue by ghost** [Jiefei-Wang/SharedObject#5]
Hello,

    Very useful package, thank you for share( it ) !

    Character type is not supported but sharing factors seems to work.

    Is it ok to convert a character vector as factors and then share it ?

Thanks

**Comment by Jiefei-Wang** [comment]
Hi,

Thanks for letting me know your concern. Fundamentally speaking, a factor vector is an integer vector with a character attribute `Levels`, so sharing a factor vector means sharing its integer part and leave the attribute unshared. For your question, it all depends on the redundancy of the character vector. If most of its elements are repeated, converting it into a factor vector would be very efficient. However, if your vector elements are unique, you would not get any benefit from doing the conversion. I hope this can answer your question.

Best,
Jiefei

**Comment by ghost** [comment]
Hi,

   Thanks for your clear explanations. 
   Yes, the character vector has a lot of repetitions, in fact, it is a column of a big data.frame.
   I need to fork several R workers that need to have ( read only ) access to that data.frame without having their own copy.
   But, without your package, even if the workers are forked and do not modify that data.frame, there are R memory issues and the workers eat the OS memory. I have read that it is because of GC issues and I did not found any way to fix that except using your really useful package.

    Is the following code correct : 

```
library( SharedObject )
library( parallel )

cluster <- makeForkCluster(1)

aHugeDataFrame <- data.frame( aColumn = as.factor( letters ), anotherColumn = 1:26 )
dfShared <- share( aHugeDataFrame )
clusterExport( cluster, "dfShared" )

# Seems to be OK
clusterEvalQ( cluster, {  dfShared[1,1] == "a"  } )

# Is this the non shared size  ?
notSharedSize <- object.size( attr( dfShared$aColumn, "levels" ) )

```

Best regards,

**Comment by Jiefei-Wang** [comment]
Hi, 

If that is the case, I think doing the conversion can be very beneficial. For your code, the only unshared part is the attributes of `dfShared$aColumn`, you can confirm it via:
```
> is.shared(dfShared$aColumn, showAttributes = TRUE)
[1] TRUE
attr(,"sharedAttributes")
attr(,"sharedAttributes")$levels
[1] FALSE

attr(,"sharedAttributes")$class
[1] FALSE
```

Please let me know if you have more questions.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment]
Hi @f4821c3 , I think I get an idea of how to share a character vector. Since I am working on another project, it would not be available soon, but I will keep this issue alive and bring this new feature into the package once I have time.

Best,
Jiefei

**Comment by ghost** [comment]
Hi Jiefi, many thanks, it will be great !
I cannot help with the implementation but if I can help in any other way, I will be happy to do so.

Thanks again

**Comment by Jiefei-Wang** [comment]
Hi, the devel version supports sharing character vector now. You can find the installation instruction from the [landing page](https://bioconductor.org/packages/devel/bioc/html/SharedObject.html) of Bioconductor. I will keep this issue open for a few days. Please let me know if you have any more questions.

Cheers,
Jiefei
