### ISSUE TITLE
Sharing of character vectors, lists and dataframes

### ISSUE THREAD

**Issue by traversc** [Jiefei-Wang/SharedObject#9]
Nice package. Do you plan to support character vectors as an altrep type? 

I'd also be interested in higher level functions that recursively share objects in lists and dataframes.

**Comment by Jiefei-Wang** [comment]
Hi @traversc, the support for character vectors will be added in the devel version, see issue https://github.com/Jiefei-Wang/SharedObject/issues/5

For list and data.frame, they have been supported by the latest release version of the package. It works exactly as you described. Please update your package for enjoying the new features.

Best,
Jiefei

**Comment by Jiefei-Wang** [comment]
Hi, the devel version supports sharing character vector now. You can find the installation instruction from the [landing page](https://bioconductor.org/packages/devel/bioc/html/SharedObject.html) of Bioconductor. I will keep this issue open for a few days. Please let me know if you have any more questions.

Cheers,
Jiefei
